{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
  namespace: {{ .Values.httproute.namespace }}
spec:
  hostnames: {{ toYaml .Values.httproute.hostnames | nindent 4 }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: httpbin
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
  {{- end }}
