name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Determine Changed Chart
        id: find-chart
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before || 'HEAD~1' }} ${{ github.sha }})

          # Find the first changed chart directory
          for file in $CHANGED_FILES; do
            if [[ $file =~ charts/(applications|utils)/.* ]]; then
              echo "chart_dir=$(dirname $file)" >> $GITHUB_ENV
              break
            fi
          done

          if [ -z "$chart_dir" ]; then
            echo "No changed charts found. Exiting."
            exit 0
          fi

      - name: Package Helm chart
        if: env.chart_dir
        run: |
          helm package $chart_dir -d ./packages

      - name: Publish Helm chart to Gitea
        if: env.chart_dir
        env:
          GITEA_URL: "gitea.lab1.nekolabs.cc" # URL of your Gitea server
          GITEA_TOKEN: "${{ secrets.ACT_RUNNER_TOKEN }}" # Gitea Personal Access Token stored as a secret
          GITEA_OWNER: "greyeye"   # Gitea user/org where the package is published
          GITEA_REPO: "helm-charts"           # Gitea repo where the chart is stored
        run: |
          CHART_FILE=$(find ./packages -type f -name "*.tgz")
          if [ -z "$CHART_FILE" ]; then
            echo "Error: No chart package found."
            exit 1
          fi

          # Add the Gitea Helm repository
          helm registry login --username $GITEA_OWNER --password $GITEA_TOKEN $GITEA_URL/$GITEA_OWNER/$GITEA_REPO

          # Push the chart to the Gitea Helm repository
          helm push $CHART_FILE oci://GITEA_URL/$GITEA_OWNER/$GITEA_REPO

          echo "Helm chart uploaded successfully."
