name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - 'charts/**'
      - 'chart/**'

env:
  REGISTRY_HOST: gitea.lab1.nekolabs.cc
  REGISTRY_USERNAME: ${{ gitea.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.ACT_RUNNER_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ gitea.actor }}"
          git config user.email "${{ gitea.actor }}@users.noreply.${{ env.REGISTRY_HOST }}"

      - name: Run chart-releaser
        uses: https://github.com/thpham/helm-oci-charts-releaser@v1
        with:
          oci_registry: ${{ env.REGISTRY_HOST }}/${{ gitea.repository_owner }}
          oci_username: ${{ gitea.repository_owner }}
          oci_password: ${{ secrets.ACT_RUNNER_TOKEN }}
          gitea_server: ${{ env.REGISTRY_HOST }}
          gitea_token: ${{ secrets.GITEA_TOKEN }}
          tag_name_pattern: '{chartName}-chart'
