name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Determine Changed Chart
        id: find-chart
        run: |
          # Fallback to HEAD~1 if github.event.before is unavailable
          BEFORE_COMMIT=${{ github.event.before || 'HEAD~1' }}
          CHANGED_FILES=$(git diff --name-only $BEFORE_COMMIT ${{ github.sha }})

          # Find the first changed chart directory
          for file in $CHANGED_FILES; do
            if [[ $file =~ charts/(applications|utils)/.* ]]; then
              echo "chart_dir=$(dirname $file)" >> $GITHUB_ENV
              break
            fi
          done

          if [ -z "$chart_dir" ]; then
            echo "No changed charts found. Exiting."
            exit 0
          fi


      - name: Package Helm chart
        if: env.chart_dir
        run: |
          helm package $chart_dir -d ./packages

      - name: Use Go Action
        id: use-go-action
        uses: actions/release-action@main
        with:
          files: |-
            packages/**
          api_key: '${{secrets.ACT_RUNNER_TOKEN}}'